### ISSUE TITLE
Class not prepared for SikuliX in MacOS

### ISSUE THREAD

**Issue by RogerAbyss** [RaiMan/sikulix4python#11]
Class not prepared for SikuliX in MacOS

`Traceback (most recent call last):
  File "Main.py", line 17, in start
    from Client.SocketClient import Client
  File "/Users/vt100i/Desktop/ST/dcs1000_AutoTest/PointW_Mac/Win/Client/SocketClient/Client.py", line 5, in <module>
    from Client.SocketClient import Exe_keyword
  File "/Users/vt100i/Desktop/ST/dcs1000_AutoTest/PointW_Mac/Win/Client/SocketClient/Exe_keyword.py", line 10, in <module>
    from Client.Libraries import WhiteBoardKeywords
  File "/Users/vt100i/Desktop/ST/dcs1000_AutoTest/PointW_Mac/Win/Client/Libraries/WhiteBoardKeywords.py", line 4, in <module>
    from Client.Libraries.Recognise.sikulix4python import *
  File "/Users/vt100i/Desktop/ST/dcs1000_AutoTest/PointW_Mac/Win/Client/Libraries/Recognise/sikulix4python/__init__.py", line 3, in <module>
    from . sxundotted import *
  File "/Users/vt100i/Desktop/ST/dcs1000_AutoTest/PointW_Mac/Win/Client/Libraries/Recognise/sikulix4python/sxundotted.py", line 3, in <module>
    SCREEN = Screen()
  File "/Users/vt100i/Desktop/ST/dcs1000_AutoTest/PointW_Mac/Win/Client/Libraries/Recognise/sikulix4python/sxbase.py", line 24, in __init__
    raise Exception("Class not prepared for SikuliX")
Exception: Class not prepared for SikuliX`

java: "1.8.0_251"
python: 2.7.16
sikulixapi: 2.0.5

please help me~ @RaiMan

**Comment by RaiMan** [comment]
Generally on recent macOS you should use Java 11 or 17.

Do you have allowed SystemSettings -> Privacy -> Assistive Devices and ScreenRecording accordingly?

I am sorry, this project is currently on hold, so you have to find your own way or use the underlying dependency directly or equivalent packages.
